### ISSUE TITLE
While building package

### ISSUE THREAD

**Issue by oorabona** [gadicc/fview-flex#10]
Hello Gadi !

I was trying to run your project locally after a git clone but the demo app could not be launched with the following error:

=> Errors while initializing project:         

While building package gadicohen:fview-flex:
error: File not found: lib/famous-flex/src/LayoutUtility.js
error: File not found: lib/famous-flex/src/LayoutContext.js
error: File not found: lib/famous-flex/src/LayoutNode.js
error: File not found: lib/famous-flex/src/FlowLayoutNode.js
error: File not found: lib/famous-flex/src/helpers/LayoutDockHelper.js
error: File not found: lib/famous-flex/src/LayoutNodeManager.js
error: File not found: lib/famous-flex/src/LayoutController.js
error: File not found: lib/famous-flex/src/ScrollController.js
error: File not found: lib/famous-flex/src/VirtualViewSequence.js
error: File not found: lib/famous-flex/src/layouts/CollectionLayout.js
error: File not found: lib/famous-flex/src/layouts/GridLayout.js
error: File not found: lib/famous-flex/src/layouts/ListLayout.js
error: File not found: lib/famous-flex/src/layouts/ProportionalLayout.js
error: File not found: lib/famous-flex/src/layouts/WheelLayout.js
error: File not found: lib/famous-flex/src/layouts/HeaderFooterLayout.js
error: File not found: lib/famous-flex/src/layouts/TabBarLayout.js
error: File not found: lib/famous-flex/src/widgets/DatePickerComponents.js
error: File not found: lib/famous-flex/src/widgets/DatePicker.js
error: File not found: lib/famous-flex/src/widgets/TabBar.js
error: File not found: lib/famous-flex/src/views/RefreshLoader.js
error: File not found: lib/famous-flex/src/views/AutosizeTextareaSurface.js
error: File not found: lib/famous-flex/src/FlexScrollView.js
error: File not found: lib/famous-flex/src/widgets/styles.css

Latest version of Meteor is installed (dev), I tried with both packaged version and Meteor 1.0.3.2 and still unsucessful.  Each time I did a bare `$ meteor` from the demo path.

Is there something I missed ? :(

**Comment by gadicc** [comment]
Hey @oorabona!

Sorry for the month delay, had to take a break from famous stuff to catch up on some of my other work which was equally lagged.

Hope you maybe figured this out.  It's because we pull in the upstream stuff via git submodules.  I've added some info about this to the bottom of the README now:

## Development

If you plan to contribute, you probably want to clone your own fork.
See https://help.github.com/articles/using-pull-requests/ for more details.

``` bash
$ git clone https://github.com/gadicc/fview-flex.git
$ cd fview-flex
$ git submodule init
$ git submodule update
```

The last two lines are necessary because we don't include all the original
fmaous-flex etc code in the repo, rather, we include them as submodules and
can update / checkout a particular commit whenever we want.  If you don't
you'll see errors like:

``` bash
=> Errors while initializing project:

While building package gadicohen:fview-flex:
error: File not found: lib/famous-flex/src/LayoutUtility.js
error: File not found: lib/famous-flex/src/LayoutContext.js
```

etc.
